### ISSUE TITLE
Error message installing epluspar package

### ISSUE THREAD

**Issue by mdakyen** [hongyuanjia/epluspar#21] opened 2020-08-30 05:55 UTC
Good day, I have been trying to install epluspar package, but I kept receiving the following error message.

Error: Failed to install 'epluspar' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Toshiba/AppData/Local/Temp/RtmpcN6aMt/file225c784e4a27/epluspar_0.0.0.9000.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by hongyuanjia** [comment] 2020-08-31 06:47
Hi @mdakyen , are there any other error messages besides this? Current messages did not give insights on why it failed.

epluspar depends on rstan, which needs some efforts to install. Can you try to install [rstan](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) before installing epluspar?

**Comment by mdakyen** [comment] 2020-09-01 03:51
Hello @hongyuanjia, thanks for your quick responds to my message.
I followed the suggestion you made earlier on, to install [https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started](url) before installing epluspar. 
But, I still encounter an error message in an attempt to install epluspar. The error message is shown bellow:
installing to C:/Users/Toshiba/Documents/R/win-library/4.0/00LOCK-epluspar/00new/epluspar/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
Error in get("assert", envir = asNamespace("eplusr"), inherits = FALSE) : 
  object 'assert' not found
Error: unable to load R code in package 'epluspar'
Execution halted
ERROR: lazy loading failed for package 'epluspar'
* removing 'C:/Users/Toshiba/Documents/R/win-library/4.0/epluspar'
Error: Failed to install 'epluspar' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Toshiba/AppData/Local/Temp/RtmpcHRUuA/file203c138b4876/epluspar_0.0.0.9000.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by hongyuanjia** [comment] 2020-09-01 04:54
Hi @mdakyen. Thanks for the info.

The error was caused by the recent update of eplusr package that epluspar depends on. It should be fixed now via #19. Please try to install again to see if it works.

**Comment by mdakyen** [comment] 2020-09-01 09:40
Hello @hongyuanjia. I wish to express my appreciation for your swift response to my complain.
I am now able to install epluspar package from github and load its library into R.

**Comment by hongyuanjia** [comment] 2020-09-01 09:48
Good to know that!

**Closed by hongyuanjia** 2020-09-01 09:48 UTC
Labels: install
